services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: ft_user
      POSTGRES_PASSWORD: ft_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
