spring:
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
  jwt:
    secret: ${JWT_SECRET}

server:
  forward-headers-strategy: native
